[build]
  publish = "frontend/build"
  # Use the "!" delimeter for `sed` because $API_LOCATION has "/" in it.
  command = "sed -i s!API_PLACEHOLDER!${API_LOCATION}!g netlify.toml && cd frontend && yarn build"

[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  NODE_ENV = "production"
  # Production defaults:
  REACT_APP_ACE_STAGING = "no"
  API_LOCATION = "hkl4dcafa7.execute-api.us-west-1.amazonaws.com/production"
  # This should have no effect, but just in case:
  REACT_APP_ACE_API = "yes"

[context.production.environment] # This is the "master" branch
  REACT_APP_ACE_STAGING = "no"
  API_LOCATION = "hkl4dcafa7.execute-api.us-west-1.amazonaws.com/production"

[context.deploy-preview.environment]
  # Pull request previews
  REACT_APP_ACE_STAGING = "yes"
  API_LOCATION = "9vugrnkufd.execute-api.us-west-1.amazonaws.com/staging"

[context.branch-deploy.environment]
  # This is any other branch
  REACT_APP_ACE_STAGING = "yes"
  API_LOCATION = "9vugrnkufd.execute-api.us-west-1.amazonaws.com/staging"

[[redirects]]
  from = "/api/*"
  to = "https://API_PLACEHOLDER/:splat" # Replaced via the build command above.
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
