version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "acephysics-staging"
s3_prefix = "acephysics-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-133fbbcrio24q"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"staging\""
