name: CI

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build:
    name: "CI Build & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Update to NPM 10
        run: npm install -g npm@10
      - name: Install dependencies
        run: npm install
      - name: Check formatting
        run: npm run format:check
      - name: Lint
        run: npm run lint
      - name: Check types
        run: npm run types
      - name: Setup DynamoDB local
        run: docker run --name dynamodb -d -p 8000:8000 amazon/dynamodb-local &
      - name: Wait for DynamoDB
        run: node ./scripts/wait-for-dynamodb.js
      - name: Run tests
        run: npm run test
