name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Update to NPM 10
        run: npm install -g npm@10
      - name: Install dependencies
        run: npm install
      # - name: Check types
      #   run: npm run types
      # - name: Lint
      #   run: npm run lint
      - name: Setup DynamoDB local
        run: docker run --name dynamodb -d -p 8000:8000 amazon/dynamodb-local &
      - name: Wait for DynamoDB
        run: |
          max_retry=30
          counter=0
          until curl http://localhost:8000
          do
            sleep 1
            [[ counter -eq $max_retry ]] && echo "Failed!" && exit 1
            echo "Trying again. Try #$counter"
            ((counter++))
          done
      - name: Run tests
        run: npm run test
