name: Publish Beta to Production

on:
  workflow_dispatch:

jobs:
  merge-beta-to-main:
    name: Merge beta to main
    runs-on: ubuntu-latest
    steps:
      - name: Set up ACE Physics Bot GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ACE_PHYSICS_BOT_APP_ID }}
          private-key: ${{ secrets.ACE_PHYSICS_BOT_PRIVATE_KEY }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: beta
          fetch-depth: 0 # Fetch all history to make the merge possible.
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge beta into main
        run: |
          git checkout main
          git merge --no-ff beta -m "Deploy: Merge branch 'beta'"
          git push origin main
