name: Publish Beta to Production

on:
  workflow_dispatch:

jobs:
  merge-beta-to-main:
    name: Merge beta to main

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge beta into main
        run: |
          git checkout main
          git merge --no-ff beta -m "Deploy: Merge branch 'beta'"
          git push origin main
